apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: hakimsamouh/api-server:prod-1.0.3-989075f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: DB_URL
              value: "jdbc:postgresql://172.19.0.2:5432/em_db"
            - name: DB_USER
              value: "hakim"
            - name: DB_PASSWORD
              value: "zoro123"
      imagePullSecrets:
        - name: dockerhub-credi